import Link from "next/link";

export const metadata = { title: "Vérification et certification | Kelo Social" };

const sections = [
["1. Objet",<>La présente politique définit les principes applicables aux systèmes de <strong>vérification et de certification proposés ou affichés par Kelo Social</strong>.<br/><br/>Ces mécanismes ont notamment pour objectifs de permettre aux utilisateurs de mieux identifier la nature de certains comptes, de limiter les risques d’usurpation d’identité et d’améliorer la confiance sur la plateforme.<br/><br/>La vérification humaine, la certification d’un compte et le statut de certificateur de confiance constituent des mécanismes distincts.</>],
["2. Vérification humaine avec Kelo ID",<>Kelo Social peut utiliser <strong>Kelo ID</strong> afin de confirmer qu’un compte est associé à une personne ayant satisfait au processus de vérification prévu par Kelo ID.<br/><br/>Cette vérification vise notamment à limiter les faux comptes, les fermes de comptes, certaines utilisations automatisées abusives et la création massive de comptes destinés au spam.<br/><br/>Une vérification Kelo ID ne signifie pas automatiquement que le compte bénéficie d’une certification publique Kelo Social.</>],
["3. Indépendance de Kelo ID",<>Kelo ID constitue un service distinct de Kelo Social.<br/><br/>Les traitements de données nécessaires à la vérification sont encadrés par les documents juridiques et la politique de confidentialité propres à Kelo ID.<br/><br/>Kelo Social ne doit recevoir que les informations nécessaires pour déterminer le résultat ou le statut de la vérification lorsque le fonctionnement technique le permet.</>],
["4. Certification Kelo Social",<>Kelo Social peut attribuer ou afficher une certification destinée à confirmer qu’un compte a été vérifié selon les critères applicables à sa catégorie.<br/><br/>La certification peut notamment concerner une personne, une entreprise, une association ou organisation, une institution, un média, une université ou un établissement reconnu, ainsi que d’autres catégories ajoutées ultérieurement par Kelo Social.<br/><br/>La certification ne constitue pas une approbation des opinions ou publications du compte.</>],
["5. Critères de certification",<>Pour obtenir une certification, Kelo Social ou un certificateur de confiance peut demander des éléments permettant d’établir raisonnablement l’authenticité du compte.<br/><br/>Selon le type de compte, la vérification peut notamment s’appuyer sur le site officiel de l’organisation, un domaine internet officiel, des coordonnées professionnelles, des publications ou pages officielles, des informations publiques fiables, une confirmation provenant de l’organisation concernée ou d’autres éléments pertinents permettant d’établir l’authenticité.<br/><br/>Les critères peuvent différer selon la catégorie du compte.</>],
["6. Certification des entreprises et organisations",<>Pour une entreprise, association, institution, université, média ou autre organisation, Kelo Social peut notamment vérifier la correspondance entre le compte et le site officiel, le domaine utilisé, les coordonnées officielles, les informations publiquement disponibles ou une personne autorisée à représenter l’organisation.<br/><br/>Kelo Social peut refuser une certification lorsque les informations disponibles ne permettent pas d’établir suffisamment l’authenticité du compte.</>],
["7. Certificateurs de confiance",<>Kelo Social peut autoriser certaines personnes ou organisations à devenir <strong>certificateurs de confiance</strong>.<br/><br/>Un certificateur de confiance peut être autorisé à délivrer certaines certifications Kelo Social selon les permissions et catégories qui lui sont attribuées.<br/><br/>Ce statut n’accorde pas un contrôle administratif général sur Kelo Social.</>],
["8. Obligations des certificateurs de confiance",<>Un certificateur de confiance doit effectuer les vérifications avec sérieux, utiliser des sources suffisamment fiables, ne pas certifier volontairement un compte qu’il sait frauduleux, éviter les conflits d’intérêts susceptibles de compromettre la vérification, respecter la confidentialité des informations non publiques obtenues dans le cadre d’une vérification et respecter les règles et procédures de Kelo Social.<br/><br/>Il est interdit de vendre ou d’échanger une certification Kelo Social sans autorisation explicite de Kelo Social.</>],
["9. Responsabilité du certificateur",<>Chaque certificateur est responsable des certifications qu’il délivre dans les limites de ses permissions.<br/><br/>Kelo Social peut examiner les certifications accordées par un certificateur afin de vérifier le respect des critères applicables.</>],
["10. Retrait du statut de certificateur de confiance",<>Kelo Social peut suspendre ou retirer le statut de certificateur de confiance notamment en cas de certifications frauduleuses, de vérifications manifestement insuffisantes répétées, d’abus des outils de certification, de vente non autorisée de certifications, de conflit d’intérêts dissimulé, de compromission du compte du certificateur ou de violation grave ou répétée des règles de Kelo Social.<br/><br/>Les certifications précédemment délivrées peuvent être réexaminées.</>],
["11. Affichage de la certification",<>Une certification Kelo Social peut être représentée par un <strong>badge ou autre indicateur visuel</strong> à proximité du nom ou du profil du compte.<br/><br/>L’apparence du badge, notamment sa forme, sa couleur, ses animations ou son emplacement, fait partie de l’identité visuelle de Kelo Social lorsqu’elle constitue une création propre au service.<br/><br/>La présence du badge indique uniquement que le compte satisfait ou a satisfait aux critères de certification applicables.</>],
["12. Informations sur une certification",<>Kelo Social peut permettre à l’utilisateur de consulter des informations complémentaires concernant une certification.<br/><br/>Cela peut notamment comprendre le type de certification, le certificateur, la date de certification, le statut actuel et d’autres informations publiques pertinentes.</>],
["13. Plusieurs certifications",<>Un compte peut, lorsque le système le permet, recevoir plusieurs certifications provenant de différents certificateurs.<br/><br/>Kelo Social peut afficher ces certifications séparément ou les regrouper dans son interface.</>],
["14. Certifications provenant de Bluesky ou de tiers",<>Kelo Social peut également afficher des certifications ou informations de vérification provenant de <strong>Bluesky ou d’autres services compatibles avec AT Protocol</strong> lorsqu’elles sont techniquement accessibles et utilisables.<br/><br/>Ces certifications restent émises par leur fournisseur respectif.<br/><br/>Leur affichage par Kelo Social ne signifie pas que Kelo Social les a délivrées.</>],
["15. Distinction visuelle",<>Kelo Social peut utiliser une identité visuelle différente afin de permettre aux utilisateurs de distinguer une certification Kelo Social, une certification délivrée par un certificateur de confiance, une vérification provenant d’un service tiers et une vérification humaine Kelo ID.<br/><br/>Kelo Social peut modifier l’apparence de ces indicateurs afin d’améliorer leur compréhension.</>],
["16. Modification d’un compte certifié",<>Une modification importante d’un compte certifié peut entraîner une nouvelle vérification.<br/><br/>Cela peut notamment concerner un changement important de nom, un changement de domaine, un transfert du compte, un changement d’organisation représentée ou une modification créant un doute sérieux concernant l’identité du titulaire.<br/><br/>La certification peut être temporairement suspendue pendant la vérification.</>],
["17. Retrait d’une certification",<>Kelo Social peut retirer ou suspendre une certification notamment lorsque le compte n’est plus authentique, la certification a été obtenue frauduleusement, les informations utilisées lors de la vérification étaient fausses, le compte change complètement d’identité ou de propriétaire, le certificateur a commis une erreur importante, le badge est utilisé de manière trompeuse ou une violation grave des règles justifie son retrait.<br/><br/>Le retrait d’une certification n’entraîne pas nécessairement la suspension du compte.</>],
["18. Certification et modération",<>Un compte certifié reste soumis aux <strong>mêmes règles de communauté et de modération</strong> que les autres utilisateurs.<br/><br/>La certification ne confère aucun privilège permettant d’enfreindre les règles de Kelo Social.<br/><br/>Un compte certifié peut donc faire l’objet d’un avertissement, d’une restriction, d’une suspension ou de toute autre mesure prévue par les règles de modération.</>],
["19. Usurpation des badges",<>Il est interdit d’utiliser un élément graphique ou une présentation destinée à faire croire qu’un compte possède une certification Kelo Social lorsqu’aucune certification n’a été accordée.<br/><br/>Kelo Social peut prendre des mesures contre les comptes utilisant de faux badges ou cherchant volontairement à tromper les utilisateurs sur leur statut.</>],
["20. Propriété intellectuelle",<>Les badges, éléments graphiques et présentations originales créés spécifiquement pour le système de certification Kelo Social peuvent être protégés par les droits de propriété intellectuelle applicables.<br/><br/>La reproduction d’un badge dans le but de créer une fausse certification, de faire croire à une affiliation inexistante ou d’imiter frauduleusement le système officiel de Kelo Social est interdite.<br/><br/>Cette disposition ne revendique aucun droit sur les badges, marques ou systèmes de certification appartenant à Bluesky ou à d’autres tiers.</>],
["21. Absence de garantie générale",<>Une certification confirme uniquement les éléments vérifiés dans le cadre du processus applicable.<br/><br/>Elle ne garantit pas l’exactitude de toutes les publications du compte, la qualité de ses produits ou services, ses opinions, son comportement futur ou l’absence de compromission ultérieure du compte.<br/><br/>Les utilisateurs doivent continuer à exercer leur propre jugement.</>],
["22. Erreurs et contestations",<>Un utilisateur peut contacter Kelo Social lorsqu’il estime qu’une certification lui a été retirée par erreur, qu’un compte certifié usurpe une identité, qu’une certification a été attribuée frauduleusement ou qu’un certificateur de confiance abuse de ses permissions.<br/><br/>Kelo Social peut réexaminer la certification et prendre les mesures appropriées.</>],
["23. Évolution du système",<>Le système de certification de Kelo Social peut évoluer avec le développement de la plateforme et d’AT Protocol.<br/><br/>Kelo Social peut notamment modifier les catégories disponibles, les critères, les badges, les permissions des certificateurs, les informations affichées et les procédures de vérification.<br/><br/>Les changements importants peuvent entraîner une mise à jour de la présente politique.</>],
["24. Contact",<><strong>Kelo Social</strong><br/><strong>M Maréchal</strong><br/><strong>Belgique — Province de Liège, Esneux</strong><br/><strong>E-mail :</strong> contact@kelosocial.eu</>],
] as const;

export default function VerificationPolicyPage(){return <main className="min-h-screen bg-kelo-background px-4 py-10 text-kelo-text sm:px-6"><article className="mx-auto max-w-4xl rounded-3xl border border-kelo-border bg-white p-6 shadow-kelo sm:p-10"><Link href="/" className="text-sm font-bold text-kelo-primary hover:underline">← Retour à Kelo Social</Link><h1 className="mt-6 text-3xl font-black sm:text-4xl">Politique de vérification et de certification — Kelo Social</h1><p className="mt-2 text-sm text-kelo-muted">Dernière mise à jour : Samedi 15 Août 2026</p><div className="mt-10 space-y-8 leading-7">{sections.map(([title,content])=><section key={title}><h2 className="text-xl font-extrabold">{title}</h2><div className="mt-3">{content}</div></section>)}</div></article></main>}
