import Link from "next/link";

export const metadata = { title: "Politique de confidentialité | Kelo Social" };

const sections = [
["1. Objet",<>La présente Politique de confidentialité explique comment <strong>Kelo Social</strong> traite les données personnelles des utilisateurs lors de l’accès et de l’utilisation de la plateforme.<br/><br/>Kelo Social accorde une importance particulière à la protection de la vie privée et entend traiter les données personnelles conformément au <strong>Règlement général sur la protection des données (RGPD – Règlement UE 2016/679)</strong> ainsi qu’aux dispositions belges applicables.</>],
["2. Responsable du traitement",<>Pour les traitements de données réalisés directement par Kelo Social :<br/><br/><strong>Responsable :</strong> M Maréchal<br/><strong>Projet :</strong> Kelo Social<br/><strong>Pays :</strong> Belgique<br/><strong>Localisation :</strong> Province de Liège, Esneux<br/><strong>E-mail :</strong> contact@kelosocial.eu<br/><strong>Site :</strong> kelosocial.eu<br/><br/>Kelo Social est actuellement un projet personnel exploité sans but lucratif et n’est ni une société commerciale ni une association constituée.</>],
["3. Fonctionnement décentralisé et AT Protocol",<>Kelo Social utilise <strong>AT Protocol</strong>, une infrastructure sociale décentralisée.<br/><br/>Les données liées à un compte AT Protocol peuvent être hébergées sur un <strong>Personal Data Server (PDS)</strong> exploité par Kelo Social ou par un fournisseur tiers choisi ou utilisé par l’utilisateur.<br/><br/>Certaines données, notamment les publications publiques et informations publiques du profil, peuvent être distribuées, indexées, synchronisées ou consultées par d’autres services compatibles avec AT Protocol.<br/><br/>Kelo Social ne contrôle pas nécessairement les traitements effectués indépendamment par les exploitants de PDS, applications, services d’indexation ou autres services tiers de l’écosystème AT Protocol.<br/><br/>Lorsqu’un service tiers agit comme responsable indépendant du traitement, sa propre politique de confidentialité s’applique.</>],
["4. Données pouvant être traitées",<>Selon les fonctionnalités utilisées, Kelo Social peut traiter notamment :<br/><br/><strong>Données du compte AT Protocol :</strong> DID, handle/nom d’utilisateur, nom d’affichage, photo de profil, biographie, PDS utilisé et informations publiques associées au compte.<br/><br/><strong>Contenus et interactions :</strong> publications, réponses, mentions, likes et autres réactions, republications, abonnements, médias publiés et autres interactions réalisées sur la plateforme.<br/><br/><strong>Données techniques et de sécurité :</strong> informations nécessaires à l’établissement et au maintien d’une session, type d’appareil ou de navigateur lorsque nécessaire, informations techniques nécessaires aux notifications, journaux techniques et informations nécessaires à la détection d’erreurs, abus ou incidents de sécurité.<br/><br/>Kelo Social cherche à limiter la collecte aux données nécessaires au fonctionnement des services concernés.</>],
["5. Connexions et suivi de sécurité",<>Kelo Social peut enregistrer certaines informations relatives aux connexions afin d’assurer la sécurité du service, prévenir les abus et permettre l’administration technique de la plateforme.<br/><br/>Cela peut notamment comprendre la date et l’heure d’une connexion, le type de connexion utilisé et certaines informations techniques nécessaires à la sécurité.<br/><br/>Lorsqu’une connexion ou une validation est réalisée au moyen d’un QR code, Kelo Social peut enregistrer les informations strictement nécessaires au fonctionnement et à la sécurisation de cette opération.<br/><br/>Ces informations ne doivent pas être utilisées pour établir un profil publicitaire des utilisateurs.</>],
["6. Kelo ID",<>Kelo Social peut s’appuyer sur <strong>Kelo ID</strong> afin de confirmer qu’un utilisateur satisfait aux exigences de vérification prévues par Kelo Social.<br/><br/>Kelo ID constitue un service distinct disposant de ses propres traitements et de sa propre politique de confidentialité.<br/><br/>Kelo Social doit recevoir uniquement les informations nécessaires à l’application du résultat de la vérification, selon le fonctionnement technique retenu.<br/><br/>Les modalités détaillées de collecte, de vérification, de conservation et de suppression des données utilisées par Kelo ID sont décrites dans la politique de confidentialité propre à Kelo ID.</>],
["7. Certifications",<>Kelo Social peut traiter les informations nécessaires à son système de certification et de certificateurs de confiance.<br/><br/>Ces informations peuvent notamment comprendre le compte concerné, le type de certification, l’émetteur de la certification, la date ou le statut de la certification et les éléments techniques nécessaires à son affichage et à sa gestion.<br/><br/>Certaines informations de certification peuvent être publiques lorsqu’elles sont destinées à être affichées sur le profil de l’utilisateur.<br/><br/>Kelo Social peut également afficher des certifications provenant de services tiers de l’écosystème AT Protocol.</>],
["8. Journal",<>La fonctionnalité <strong>Journal</strong> peut traiter et afficher les informations publiques de comptes médias ajoutés par l’administration de Kelo Social.<br/><br/>Ces informations peuvent notamment comprendre le compte AT Protocol, le nom du média, ses publications publiques ainsi que les catégories géographiques attribuées par Kelo Social, par exemple pays, continent ou portée internationale.<br/><br/>Journal ne nécessite pas que Kelo Social devienne propriétaire des publications affichées.</>],
["9. Finalités des traitements",<>Les données peuvent être traitées notamment pour fournir et faire fonctionner Kelo Social ; permettre la connexion aux comptes AT Protocol ; afficher les profils et publications ; permettre les interactions sociales ; fournir les notifications ; gérer les certifications ; fournir Journal ; assurer la sécurité du service ; prévenir les abus, le spam et la fraude ; traiter les signalements ; assurer la modération ; résoudre les problèmes techniques ; et respecter les obligations légales applicables.<br/><br/>Kelo Social n’a pas pour objectif de vendre les données personnelles des utilisateurs.</>],
["10. Bases juridiques",<>Selon le traitement concerné, Kelo Social peut s’appuyer sur les bases juridiques prévues par le RGPD, notamment l’<strong>exécution du service ou les mesures précontractuelles</strong>, l’<strong>intérêt légitime</strong>, le <strong>consentement</strong> lorsqu’il est requis et une <strong>obligation légale</strong> lorsqu’un traitement est nécessaire pour respecter la législation applicable.<br/><br/>La base juridique exacte dépend de la nature du traitement concerné.</>],
["11. Publicité et vente de données",<>Kelo Social ne vend pas les données personnelles de ses utilisateurs.<br/><br/>Kelo Social n’utilise pas les données personnelles dans le but de constituer des profils publicitaires destinés à être vendus à des annonceurs.<br/><br/>Si le modèle économique ou les pratiques de Kelo Social devaient évoluer, la présente politique devrait être mise à jour avant la mise en œuvre des traitements concernés.</>],
["12. Destinataires",<>Les données peuvent être accessibles, selon leur nature et lorsque cela est nécessaire, à Kelo Social ; aux prestataires techniques nécessaires au fonctionnement du service ; au fournisseur PDS de l’utilisateur ; aux services compatibles avec AT Protocol pour les données distribuées via le protocole ; aux services intervenant dans la vérification lorsque l’utilisateur utilise la fonctionnalité correspondante ; et aux autorités compétentes lorsqu’une obligation légale l’impose.<br/><br/>Les publications et informations configurées comme publiques peuvent être accessibles publiquement.</>],
["13. Hébergement, prestataires et transferts de données",<>Kelo Social utilise différents prestataires techniques nécessaires au fonctionnement du service.<br/><br/><strong>Vercel</strong> est utilisé pour l’hébergement et le déploiement de l’application web Kelo Social. Dans le cadre de la fourniture de ses services, Vercel peut être amené à traiter certaines données techniques nécessaires au fonctionnement, à la sécurité et à la mise à disposition du site.<br/><br/><strong>Infomaniak</strong> est utilisé notamment pour la gestion des noms de domaine et des services DNS associés à Kelo Social.<br/><br/>Certaines données liées aux comptes et publications peuvent également être hébergées sur les <strong>Personal Data Servers (PDS)</strong> utilisés dans le cadre d’AT Protocol. Un PDS peut être exploité par Kelo Social ou par un fournisseur tiers.<br/><br/>Lorsqu’un prestataire ou une infrastructure implique un transfert de données personnelles en dehors de l’Espace économique européen, les mécanismes et garanties prévus par le RGPD sont appliqués lorsqu’ils sont requis.<br/><br/>Les services tiers utilisés directement par un utilisateur, notamment un PDS indépendant, peuvent agir comme responsables distincts du traitement et appliquer leur propre politique de confidentialité.</>],
["14. Durée de conservation",<>Kelo Social conserve les données personnelles uniquement pendant la durée nécessaire aux finalités pour lesquelles elles sont traitées, sous réserve d’éventuelles obligations légales.<br/><br/>Les durées peuvent varier selon la catégorie de données. Les données de sécurité peuvent être conservées pendant une période limitée nécessaire à la détection et à l’investigation d’incidents.<br/><br/>Les données d’un compte hébergé sur un PDS tiers sont soumises également aux règles de conservation de l’exploitant de ce PDS.<br/><br/>Certaines informations publiques distribuées via AT Protocol peuvent avoir été copiées ou indexées par des services indépendants que Kelo Social ne contrôle pas.</>],
["15. Sécurité",<>Kelo Social met en œuvre des mesures techniques et organisationnelles raisonnables destinées à protéger les données contre les accès non autorisés, la perte, l’altération, la divulgation non autorisée et les utilisations abusives.<br/><br/>Aucun système informatique ne peut toutefois garantir une sécurité absolue.<br/><br/>En cas de violation de données personnelles relevant de la responsabilité de Kelo Social, les obligations prévues par le RGPD sont appliquées, notamment en matière d’évaluation, de documentation et, lorsque cela est requis, de notification.</>],
["16. Droits des utilisateurs",<>Dans les conditions prévues par le RGPD, une personne concernée peut notamment disposer d’un <strong>droit d’accès</strong>, d’un <strong>droit de rectification</strong>, d’un <strong>droit à l’effacement</strong>, d’un <strong>droit à la limitation du traitement</strong>, d’un <strong>droit d’opposition</strong>, d’un <strong>droit à la portabilité</strong> lorsque celui-ci est applicable et du <strong>droit de retirer son consentement</strong> lorsqu’un traitement repose sur celui-ci.<br/><br/>L’exercice d’un droit peut être soumis aux conditions et exceptions prévues par la législation.</>],
["17. Exercer ses droits",<>Pour exercer un droit relatif à un traitement réalisé par Kelo Social : <strong>contact@kelosocial.eu</strong>.<br/><br/>La demande doit permettre à Kelo Social d’identifier les données concernées. Lorsque cela est nécessaire pour éviter qu’un tiers accède frauduleusement aux données d’un utilisateur, Kelo Social peut demander des informations permettant de vérifier l’identité du demandeur.<br/><br/>Kelo Social répond aux demandes dans les délais prévus par la législation applicable.<br/><br/>Lorsqu’une donnée est exclusivement contrôlée par un PDS ou un service tiers, l’utilisateur peut devoir exercer son droit directement auprès du responsable concerné.</>],
["18. Réclamation auprès de l’autorité de contrôle",<>Toute personne concernée dispose du droit d’introduire une réclamation auprès de l’autorité de contrôle compétente.<br/><br/>En Belgique, l’autorité compétente est notamment l’<strong>Autorité de protection des données (APD)</strong>.<br/><br/>Cette possibilité n’empêche pas l’utilisateur de contacter préalablement Kelo Social afin de tenter de résoudre sa demande.</>],
["19. Cookies et stockage local",<>Kelo Social peut utiliser des cookies, le stockage local du navigateur ou des technologies similaires nécessaires notamment à la connexion, à la sécurité, aux préférences de l’utilisateur et au fonctionnement de certaines fonctionnalités.<br/><br/>Les modalités précises seront détaillées dans la <strong>Politique relative aux cookies et stockages locaux</strong>.<br/><br/>Lorsque la législation exige le consentement préalable de l’utilisateur pour une technologie donnée, celle-ci ne doit être activée qu’après obtention de ce consentement.</>],
["20. Décisions automatisées",<>Kelo Social peut utiliser des systèmes automatisés pour certaines fonctionnalités techniques, de classement, de recommandation ou de détection.<br/><br/>Kelo Social n’a pas pour objectif de soumettre les utilisateurs à une décision fondée exclusivement sur un traitement automatisé produisant des effets juridiques ou les affectant de manière similaire de façon significative, sauf si les conditions prévues par la législation applicable sont respectées.</>],
["21. Modifications",<>La présente Politique de confidentialité peut être modifiée afin de tenir compte notamment d’une évolution de Kelo Social, de nouvelles fonctionnalités, de nouveaux prestataires, d’une modification de l’infrastructure ou d’une évolution de la législation.<br/><br/>La date de dernière mise à jour est indiquée au début du document.<br/><br/>En cas de modification importante affectant les utilisateurs, Kelo Social peut mettre en place une information appropriée.</>],
["22. Contact",<><strong>Kelo Social</strong><br/><strong>M Maréchal</strong><br/><strong>Belgique — Province de Liège, Esneux</strong><br/><strong>E-mail :</strong> contact@kelosocial.eu</>],
] as const;

export default function PrivacyPage(){return <main className="min-h-screen bg-kelo-background px-4 py-10 text-kelo-text sm:px-6"><article className="mx-auto max-w-4xl rounded-3xl border border-kelo-border bg-white p-6 shadow-kelo sm:p-10"><Link href="/" className="text-sm font-bold text-kelo-primary hover:underline">← Retour à Kelo Social</Link><h1 className="mt-6 text-3xl font-black sm:text-4xl">Politique de confidentialité et de protection des données — Kelo Social</h1><p className="mt-2 text-sm text-kelo-muted">Dernière mise à jour : Samedi 15 Août 2026</p><div className="mt-10 space-y-8 leading-7">{sections.map(([title,content])=><section key={title}><h2 className="text-xl font-extrabold">{title}</h2><div className="mt-3">{content}</div></section>)}</div></article></main>}
