import { createAtpAgent } from "@/lib/atproto/client";
import { AtprotoDiscoveryError, discoverAccount } from "@/lib/atproto/discovery";
import { sessionStorage } from "@/lib/session/session-storage";
import { AtpSession, LoginCredentials, SignupPayload } from "@/types/auth";

export class AuthError extends Error { constructor(message:string){super(message);this.name="AuthError";} }
export class AuthFactorRequiredError extends AuthError { constructor(){super("Un code de connexion a été envoyé à votre adresse e-mail. Saisissez-le pour continuer.");this.name="AuthFactorRequiredError";} }
let cachedAgent:ReturnType<typeof createAtpAgent>|null=null;let cachedSessionKey:string|null=null;let pendingSessionRefresh:Promise<AtpSession>|null=null;
const BLUESKY_ENTRYWAY_URL="https://bsky.social";
function getSessionKey(s:AtpSession){return[s.did,s.pdsUrl,s.accessJwt,s.refreshJwt].join("|")}
function clearCachedAgent(){cachedAgent=null;cachedSessionKey=null}
function saveSession(s:AtpSession){sessionStorage.set(s);clearCachedAgent()}
function normalizePdsUrl(v:string){return v.trim().replace(/\/$/,"")}
function getLoginServiceForPds(pdsUrl:string){try{const h=new URL(pdsUrl).hostname.toLowerCase();if(h==="bsky.social"||h.endsWith(".host.bsky.network"))return BLUESKY_ENTRYWAY_URL}catch{}return normalizePdsUrl(pdsUrl)}
function isDefinitelyExpiredSessionStatus(s:number){return s===400||s===401||s===403}
function isAuthFactorRequired(error:any){const code=String(error?.error||error?.response?.data?.error||error?.data?.error||"");const msg=String(error?.message||"");return code==="AuthFactorTokenRequired"||/auth.?factor|verification code|login code/i.test(msg)}
async function refreshAtProtocolSession(session:AtpSession):Promise<AtpSession>{if(pendingSessionRefresh)return pendingSessionRefresh;pendingSessionRefresh=(async()=>{if(!session.refreshJwt)throw new AuthError("Votre session ne peut pas être renouvelée. Veuillez vous reconnecter.");const service=getLoginServiceForPds(session.pdsUrl);let response:Response;try{response=await fetch(`${service}/xrpc/com.atproto.server.refreshSession`,{method:"POST",headers:{Authorization:`Bearer ${session.refreshJwt}`,Accept:"application/json"},cache:"no-store"})}catch(e){throw e}if(!response.ok){if(isDefinitelyExpiredSessionStatus(response.status))throw new AuthError("Votre session a expiré. Veuillez vous reconnecter.");throw new Error(`Le PDS est temporairement indisponible pendant le renouvellement de session (${response.status}).`)}const d=await response.json() as any;if(!d.accessJwt||!d.refreshJwt||!d.handle||!d.did)throw new AuthError("Le PDS a retourné une session incomplète.");if(d.did!==session.did)throw new AuthError("La session renouvelée ne correspond pas au compte connecté.");const next={accessJwt:d.accessJwt,refreshJwt:d.refreshJwt,handle:d.handle,did:d.did,pdsUrl:session.pdsUrl};saveSession(next);return next})();try{return await pendingSessionRefresh}finally{pendingSessionRefresh=null}}
export async function login(credentials:LoginCredentials):Promise<AtpSession>{const identifier=credentials.identifier.trim().replace(/^@/,"").toLowerCase();if(!identifier)throw new AuthError("Veuillez saisir votre identifiant AT Protocol.");if(!credentials.password)throw new AuthError("Veuillez saisir votre mot de passe.");let discoveredAccount;try{discoveredAccount=await discoverAccount(identifier)}catch(e){if(e instanceof AtprotoDiscoveryError)throw new AuthError(e.message);throw new AuthError("Impossible de trouver le serveur PDS associé à ce compte.")}const loginService=getLoginServiceForPds(discoveredAccount.pdsUrl);const agent=createAtpAgent(loginService);try{await agent.login({identifier:discoveredAccount.identifier,password:credentials.password,...(credentials.authFactorToken?{authFactorToken:credentials.authFactorToken.trim()}: {})} as any)}catch(error:any){console.error("AT Protocol login error:",{identifier:discoveredAccount.identifier,pds:discoveredAccount.pdsUrl,loginService,error:error?.error||error?.message});if(isAuthFactorRequired(error))throw new AuthFactorRequiredError();const message=String(error?.message||"");if(/invalid.*(password|identifier)|authentication required/i.test(message))throw new AuthError("Identifiant ou mot de passe incorrect.");throw new AuthError(`Connexion AT Protocol impossible${message?`: ${message}`:"."}`)}if(!agent.session)throw new AuthError("La connexion a échoué : aucune session n’a été retournée par le PDS.");if(agent.session.did!==discoveredAccount.did)throw new AuthError("La session retournée ne correspond pas à l’identité AT Protocol demandée.");const session={accessJwt:agent.session.accessJwt,refreshJwt:agent.session.refreshJwt,handle:agent.session.handle,did:agent.session.did,pdsUrl:discoveredAccount.pdsUrl};sessionStorage.set(session);cachedAgent=agent;cachedSessionKey=getSessionKey(session);return session}
export async function loginWithKeloIdSession(session:AtpSession):Promise<AtpSession>{if(!session?.accessJwt||!session?.refreshJwt||!session?.handle||!session?.did||!session?.pdsUrl)throw new AuthError("Session Kelo ID incomplète.");saveSession(session);try{await resumeAgentSession(session);const current=getStoredSession();if(!current)throw new AuthError("La session Kelo ID n’a pas pu être enregistrée.");if(current.did!==session.did)throw new AuthError("La session Kelo ID ne correspond pas au compte confirmé.");return current}catch(e){if(e instanceof AuthError)throw e;throw new AuthError("La session transmise par Kelo ID ne peut pas être validée. Scannez un nouveau QR.")}}
export function logout(){clearCachedAgent();sessionStorage.clear()}
export function getStoredSession(){return sessionStorage.get()}
export async function resumeAgentSession(session:AtpSession){const key=getSessionKey(session);if(cachedAgent&&cachedSessionKey===key)return cachedAgent;const resume=async(active:AtpSession)=>{const agent=createAtpAgent(getLoginServiceForPds(active.pdsUrl));await agent.resumeSession({accessJwt:active.accessJwt,refreshJwt:active.refreshJwt,active:true,handle:active.handle,did:active.did});await agent.api.com.atproto.server.getSession();cachedAgent=agent;cachedSessionKey=getSessionKey(active);return agent};try{return await resume(session)}catch{try{return await resume(await refreshAtProtocolSession(session))}catch(e){clearCachedAgent();if(e instanceof AuthError){sessionStorage.clear();throw e}throw new AuthError("Connexion temporairement impossible avec votre PDS. Votre session est conservée.")}}}
export async function restoreStoredSession(){const stored=getStoredSession();if(!stored)return null;try{await resumeAgentSession(stored);return getStoredSession()||stored}catch{return getStoredSession()}}
export async function getAuthenticatedAgent(){const session=getStoredSession();if(!session)throw new AuthError("Vous devez être connecté.");const agent=await resumeAgentSession(session);return{agent,session:getStoredSession()||session}}
export async function signup(payload:SignupPayload):Promise<void>{const response=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});let data:{error?:string};try{data=await response.json()}catch{data={}}if(!response.ok)throw new AuthError(data.error||"Erreur lors de l'inscription.")}
