import Link from "next/link";

export const metadata = { title: "Conditions Générales d’Utilisation | Kelo Social" };

const sections = [
  ["1. Objet", <>Les présentes Conditions Générales d’Utilisation, ci-après « CGU », définissent les conditions d’accès et d’utilisation de <strong>Kelo Social</strong>.<br/><br/>Kelo Social est un projet personnel et non lucratif proposant un réseau social reposant notamment sur <strong>AT Protocol</strong>, un protocole permettant l’utilisation d’une infrastructure sociale décentralisée.<br/><br/>L’utilisation de Kelo Social implique le respect des présentes CGU ainsi que des autres règles et politiques applicables au service.</>],
  ["2. Éditeur", <>Kelo Social est actuellement exploité à titre personnel et sans but lucratif.<br/><br/><strong>Responsable :</strong> M Maréchal<br/><strong>Pays :</strong> Belgique<br/><strong>Localisation :</strong> Province de Liège, Esneux<br/><strong>Contact :</strong> contact@kelosocial.eu<br/><strong>Site :</strong> kelosocial.eu<br/><br/>Kelo Social n’est actuellement ni une société commerciale ni une association constituée.</>],
  ["3. Conditions d’accès", <>L’accès à certaines parties publiques de Kelo Social peut être possible sans compte.<br/><br/>La publication de contenus, les interactions avec d’autres utilisateurs et certaines fonctionnalités nécessitent un compte compatible avec AT Protocol et une connexion à Kelo Social.<br/><br/><strong>L’âge minimum pour utiliser Kelo Social est fixé à 18 ans.</strong><br/><br/>En créant un compte ou en utilisant Kelo Social, l’utilisateur déclare satisfaire aux conditions d’âge applicables.<br/><br/>Kelo Social peut mettre en place des mécanismes destinés à vérifier qu’un utilisateur satisfait aux conditions nécessaires à l’utilisation de certaines fonctionnalités.</>],
  ["4. Compte AT Protocol et PDS", <>Kelo Social repose sur AT Protocol.<br/><br/>Le compte d’un utilisateur peut être hébergé sur un <strong>Personal Data Server (PDS)</strong> exploité par Kelo Social ou par un fournisseur tiers compatible.<br/><br/>Kelo Social peut permettre la connexion à plusieurs fournisseurs/PDS.<br/><br/>Lorsqu’un utilisateur choisit un PDS exploité par un tiers, certaines opérations et données peuvent dépendre directement de ce fournisseur.<br/><br/>Kelo Social ne contrôle pas nécessairement la disponibilité, la sécurité ou les règles appliquées par les PDS tiers.<br/><br/>L’utilisateur peut par conséquent être également soumis aux conditions du fournisseur de son PDS.</>],
  ["5. Identifiants et sécurité du compte", <>L’utilisateur est responsable de la protection de ses moyens d’authentification.<br/><br/>Il ne doit pas volontairement communiquer ses mots de passe, codes de sécurité ou autres informations confidentielles permettant l’accès à son compte.<br/><br/>En cas de suspicion d’accès non autorisé, l’utilisateur est invité à sécuriser son compte et à contacter le fournisseur de son PDS lorsque cela est nécessaire.<br/><br/>Kelo Social ne demandera jamais à un utilisateur de communiquer publiquement son mot de passe.</>],
  ["6. Kelo ID et vérification humaine", <>Kelo Social peut utiliser <strong>Kelo ID</strong> afin de vérifier certaines caractéristiques nécessaires à l’accès au service ou à certaines fonctionnalités, notamment la vérification qu’un compte correspond à une personne réelle.<br/><br/>Les modalités précises de fonctionnement, les informations utilisées et les règles applicables à cette vérification sont détaillées dans la <strong>Politique de vérification et de certification</strong> et dans les documents applicables à Kelo ID.<br/><br/>La vérification Kelo ID ne constitue pas nécessairement une certification publique de l’identité ou de la notoriété de l’utilisateur.</>],
  ["7. Publications et contenus", <>Les utilisateurs peuvent notamment publier des textes, images, vidéos, liens et autres contenus compatibles avec les fonctionnalités proposées par Kelo Social et AT Protocol.<br/><br/>L’utilisateur demeure responsable des contenus qu’il publie.<br/><br/>Il doit disposer des droits ou autorisations nécessaires pour publier les contenus concernés.<br/><br/>La publication d’un contenu sur Kelo Social <strong>ne transfère pas sa propriété à Kelo Social</strong>.<br/><br/>Cependant, le fonctionnement technique d’un réseau social décentralisé peut nécessiter le traitement, la transmission, l’affichage, la mise en cache ou la reproduction technique temporaire du contenu afin de permettre son affichage et sa distribution.<br/><br/>Certaines publications peuvent également être accessibles depuis d’autres applications utilisant AT Protocol indépendamment de Kelo Social.</>],
  ["8. Comportements et contenus interdits", <>L’utilisateur s’engage à ne pas utiliser Kelo Social pour publier ou diffuser des contenus ou adopter des comportements contraires à la législation applicable ou aux règles de la communauté.<br/><br/>Sont notamment susceptibles de faire l’objet d’une intervention : contenus manifestement illicites ; harcèlement et menaces ; usurpation d’identité ; escroqueries et tentatives de fraude ; spam et comportements automatisés abusifs ; atteintes aux droits de propriété intellectuelle ; exploitation ou diffusion non autorisée de données personnelles ; contenus interdits par les règles de la communauté.<br/><br/>Les règles détaillées sont précisées dans la <strong>Politique de modération et les Règles de la communauté</strong>.</>],
  ["9. Modération", <>Kelo Social peut mettre en œuvre des mécanismes de modération afin de protéger ses utilisateurs et de faire respecter ses règles.<br/><br/>Selon la situation et les possibilités techniques disponibles, une intervention peut notamment prendre la forme d’un avertissement, d’une limitation de visibilité, d’un retrait dans les services contrôlés par Kelo Social, d’une restriction fonctionnelle, d’une suspension ou d’un bannissement.<br/><br/>Dans un environnement décentralisé, Kelo Social peut ne pas être techniquement en mesure de supprimer un contenu de tous les services, PDS ou applications indépendantes utilisant AT Protocol.<br/><br/>Les mesures prises par Kelo Social concernent donc les éléments et services sur lesquels Kelo Social dispose effectivement d’un contrôle.</>],
  ["10. Signalements et contestations", <>Les utilisateurs peuvent signaler les contenus ou comportements qu’ils estiment contraires aux règles ou à la législation applicable en utilisant les outils proposés par Kelo Social.<br/><br/>Kelo Social peut examiner ces signalements et prendre les mesures appropriées.<br/><br/>Lorsqu’une procédure de contestation est disponible, l’utilisateur concerné peut demander le réexamen d’une décision conformément aux modalités indiquées par Kelo Social.</>],
  ["11. Certifications Kelo Social", <>Kelo Social peut proposer différents mécanismes de certification ou de vérification de comptes.<br/><br/>Certaines certifications peuvent être accordées directement par Kelo Social ou par des <strong>certificateurs de confiance</strong> autorisés.<br/><br/>Une certification peut notamment servir à indiquer qu’un compte a fait l’objet d’une vérification selon certains critères.<br/><br/>Une certification ne constitue pas une garantie générale concernant toutes les publications, opinions, activités ou comportements futurs du titulaire du compte.<br/><br/>Kelo Social peut retirer une certification lorsqu’un compte ne respecte plus les critères applicables ou en cas d’utilisation abusive.<br/><br/>Les règles détaillées seront définies dans la <strong>Politique de vérification et de certification</strong>.</>],
  ["12. Certifications provenant de services tiers", <>Kelo Social peut afficher des informations de vérification ou de certification provenant de services tiers de l’écosystème AT Protocol, notamment lorsque ces informations sont publiquement disponibles via le protocole.<br/><br/>L’affichage d’une certification provenant d’un tiers ne signifie pas que Kelo Social en est l’émetteur.<br/><br/>Les règles du fournisseur ayant délivré cette certification restent applicables.</>],
  ["13. Journal", <>Kelo Social peut proposer une section <strong>Journal</strong> regroupant les publications de comptes médias sélectionnés par l’administration de Kelo Social.<br/><br/>La présence d’un média dans Journal ne signifie pas que Kelo Social approuve l’ensemble de ses contenus ou opinions.<br/><br/>Les publications affichées restent attribuées à leurs auteurs respectifs.<br/><br/>Kelo Social peut classer les médias notamment selon leur pays, continent ou portée internationale afin de permettre aux utilisateurs de filtrer leur fil d’actualité.<br/><br/>Kelo Social peut ajouter ou retirer un média de Journal à sa discrétion éditoriale, sous réserve des règles légales applicables.</>],
  ["14. Algorithmes et fils personnalisés", <>Kelo Social peut proposer différents systèmes de recommandation, de classement ou de personnalisation des publications.<br/><br/>Lorsque cette possibilité est proposée, l’utilisateur peut disposer de paramètres lui permettant d’influencer le fonctionnement ou l’intensité de certaines recommandations.<br/><br/>Ces systèmes peuvent évoluer au cours du développement de Kelo Social.</>],
  ["15. Notifications", <>Kelo Social peut proposer des notifications relatives notamment aux mentions, réponses, abonnements, réactions, republications, citations, messages ou autres interactions.<br/><br/>L’utilisateur peut disposer de paramètres permettant d’activer ou désactiver certaines catégories de notifications.<br/><br/>Certaines notifications système nécessitent l’autorisation du navigateur ou du système d’exploitation de l’utilisateur.</>],
  ["16. Propriété intellectuelle de Kelo Social", <>L’utilisation de Kelo Social ne confère à l’utilisateur aucun droit de propriété sur <strong>Kelo Social, son code source propriétaire, son identité visuelle, son logo, ses créations graphiques, ses textes originaux ou ses éléments d’interface protégés</strong>.<br/><br/>Sauf autorisation du titulaire des droits ou exception prévue par la loi, toute reproduction, adaptation, distribution, extraction, commercialisation ou exploitation non autorisée d’un élément protégé est interdite.<br/><br/>Il est notamment interdit d’utiliser l’identité, les éléments graphiques ou les signes distinctifs de Kelo Social d’une manière susceptible de créer une confusion faisant croire qu’un produit, service ou plateforme est exploité, approuvé ou officiellement associé à Kelo Social lorsqu’aucune autorisation n’a été accordée.<br/><br/>Cette protection ne s’étend pas aux technologies, protocoles, logiciels ou créations appartenant à des tiers.<br/><br/>Kelo Social ne revendique notamment aucun droit de propriété sur <strong>AT Protocol, Bluesky ou les composants open source</strong> utilisés dans le cadre du service.</>],
  ["17. Utilisation automatisée", <>L’utilisation de robots, scripts ou systèmes automatisés peut être limitée lorsque ceux-ci perturbent le fonctionnement du service, génèrent du spam, contournent les mécanismes de sécurité ou enfreignent les règles applicables.<br/><br/>Les intégrations légitimes utilisant les mécanismes prévus par AT Protocol restent soumises aux règles et limitations techniques applicables.</>],
  ["18. Suspension et restriction d’accès", <>Kelo Social peut restreindre l’accès à certaines fonctionnalités lorsqu’un utilisateur ne respecte pas les présentes CGU, les règles de la communauté ou la législation applicable.<br/><br/>La nature et la durée d’une mesure peuvent dépendre notamment de la gravité, de la répétition et du contexte du comportement concerné.<br/><br/>Lorsqu’une obligation légale l’exige, les droits de contestation ou autres garanties applicables sont respectés.</>],
  ["19. Suppression du compte", <>La gestion ou la suppression complète d’un compte AT Protocol peut dépendre du PDS sur lequel le compte est hébergé.<br/><br/>La suppression de données depuis l’interface de Kelo Social ne garantit donc pas nécessairement leur suppression immédiate de toutes les infrastructures indépendantes ayant pu recevoir ou indexer des informations publiques via AT Protocol.<br/><br/>Les utilisateurs sont invités à consulter également les règles de leur fournisseur PDS.</>],
  ["20. Services tiers", <>Kelo Social peut proposer des liens ou interactions avec des services exploités par des tiers.<br/><br/>Kelo Social n’est pas responsable du fonctionnement ou du contenu d’un service indépendant qu’il ne contrôle pas, sous réserve des responsabilités qui ne peuvent légalement être exclues.</>],
  ["21. Disponibilité et évolution de Kelo Social", <>Kelo Social est actuellement un projet en développement.<br/><br/>Des fonctionnalités peuvent être ajoutées, modifiées, suspendues ou supprimées.<br/><br/>Des interruptions peuvent également intervenir en raison de maintenance, d’incidents techniques, de mises à jour ou de dysfonctionnements de services tiers.<br/><br/>Kelo Social ne garantit pas une disponibilité permanente et ininterrompue du service.</>],
  ["22. Responsabilité", <>Chaque utilisateur est responsable de son utilisation de Kelo Social et des contenus qu’il publie.<br/><br/>Kelo Social s’efforce d’assurer un fonctionnement approprié et sécurisé de son service.<br/><br/>Kelo Social ne saurait cependant être tenu responsable d’un dysfonctionnement directement imputable à une infrastructure tierce qu’il ne contrôle pas, sous réserve des responsabilités qui ne peuvent légalement être exclues.<br/><br/>Aucune disposition des présentes CGU n’a pour objet de supprimer ou limiter les droits impératifs reconnus aux utilisateurs par la législation applicable.</>],
  ["23. Protection des données personnelles", <>Le traitement des données personnelles réalisé dans le cadre de Kelo Social est décrit dans la <strong>Politique de confidentialité</strong>.<br/><br/>Les informations concernant les cookies et technologies similaires sont décrites dans la <strong>Politique relative aux cookies et stockages locaux</strong>.</>],
  ["24. Modification des CGU", <>Kelo Social peut modifier les présentes CGU notamment afin de tenir compte d’une évolution du service, d’une nouvelle fonctionnalité, d’une modification technique ou d’une évolution des obligations légales.<br/><br/>La date de dernière mise à jour est indiquée au début du document.<br/><br/>Lorsqu’une modification importante le nécessite, Kelo Social peut informer les utilisateurs par un moyen approprié.</>],
  ["25. Droit applicable", <>Les présentes CGU sont régies par le <strong>droit belge</strong>, sous réserve des dispositions impératives applicables du droit belge et européen.<br/><br/>En cas de différend, une résolution amiable peut être recherchée préalablement lorsque cela est approprié.<br/><br/>Les juridictions compétentes sont déterminées conformément aux règles légales applicables.</>],
  ["26. Contact", <><strong>Kelo Social</strong><br/><strong>E-mail :</strong> contact@kelosocial.eu<br/><strong>Belgique — Province de Liège, Esneux</strong></>],
] as const;

export default function TermsPage(){return <main className="min-h-screen bg-kelo-background px-4 py-10 text-kelo-text sm:px-6"><article className="mx-auto max-w-4xl rounded-3xl border border-kelo-border bg-white p-6 shadow-kelo sm:p-10"><Link href="/" className="text-sm font-bold text-kelo-primary hover:underline">← Retour à Kelo Social</Link><h1 className="mt-6 text-3xl font-black sm:text-4xl">Conditions Générales d’Utilisation — Kelo Social</h1><p className="mt-2 text-sm text-kelo-muted">Dernière mise à jour : Samedi 15 Août 2025</p><div className="mt-10 space-y-8 leading-7">{sections.map(([title,content])=><section key={title}><h2 className="text-xl font-extrabold">{title}</h2><div className="mt-3">{content}</div></section>)}</div></article></main>}
