import Link from "next/link";

export const metadata = { title: "Règles de la communauté et modération | Kelo Social" };

const sections = [
["1. Objet",<>Les présentes règles définissent les comportements attendus sur <strong>Kelo Social</strong> ainsi que les principes appliqués lors de la modération des contenus et des comptes.<br/><br/>L’objectif est de maintenir un espace respectueux, sûr et compatible avec la législation applicable, tout en tenant compte du fonctionnement décentralisé d’AT Protocol.</>],
["2. Principe général",<>Chaque utilisateur reste responsable de ses publications, messages, médias et interactions.<br/><br/>L’utilisation de Kelo Social doit se faire dans le respect de la législation applicable, des présentes règles, des Conditions Générales d’Utilisation, des droits des autres utilisateurs et des règles éventuellement applicables au PDS utilisé.</>],
["3. Respect des personnes",<>Les comportements visant à intimider, harceler, menacer ou humilier volontairement une personne ou un groupe peuvent faire l’objet de mesures de modération.<br/><br/>Sont notamment concernés : harcèlement répété, menaces crédibles, intimidation, incitation au harcèlement et publication abusive d’informations personnelles dans le but de nuire.</>],
["4. Discours haineux",<>Les contenus attaquant ou déshumanisant des personnes en raison notamment de caractéristiques protégées par la législation applicable peuvent faire l’objet d’une intervention.<br/><br/>Cela peut notamment concerner les attaques fondées sur l’origine, la nationalité, la couleur de peau, la religion ou conviction, le sexe, l’orientation sexuelle, l’identité ou l’expression de genre, le handicap ou d’autres caractéristiques protégées.<br/><br/>Les discussions, critiques ou débats sur des idées, croyances ou institutions restent possibles lorsqu’ils ne constituent pas une attaque interdite contre des personnes.</>],
["5. Violences et menaces",<>Les menaces de violence crédibles, l’incitation directe à commettre des violences ou certains contenus faisant l’apologie de violences graves peuvent être supprimés ou faire l’objet d’autres mesures.<br/><br/>Les contenus informatifs, journalistiques, éducatifs ou historiques peuvent être évalués en tenant compte de leur contexte.</>],
["6. Exploitation et atteintes sexuelles",<>Les contenus impliquant l’exploitation sexuelle, les violences sexuelles ou toute représentation sexuelle illégale sont interdits.<br/><br/>Tout contenu concernant l’exploitation sexuelle de mineurs est strictement interdit et peut être signalé aux autorités compétentes lorsque la législation l’exige.</>],
["7. Contenus illégaux",<>Kelo Social peut intervenir contre tout contenu manifestement contraire à la législation applicable.<br/><br/>Cela peut notamment concerner certaines escroqueries, certains contenus terroristes illégaux, l’exploitation sexuelle, certaines menaces, la vente ou diffusion illégale de biens ou services et certaines violations graves des droits de propriété intellectuelle.</>],
["8. Usurpation d’identité",<>Il est interdit d’usurper l’identité d’une autre personne, entreprise, association, institution ou organisation dans le but de tromper les utilisateurs.<br/><br/>Les comptes parodiques, satiriques ou de fans peuvent être autorisés lorsqu’ils indiquent clairement leur nature et ne cherchent pas à créer une confusion trompeuse.</>],
["9. Spam et manipulation",<>Les comportements abusifs destinés à perturber Kelo Social ou manipuler artificiellement les interactions peuvent être limités.<br/><br/>Cela peut notamment inclure la publication massive et répétitive de contenus identiques, les mentions abusives, la création massive de comptes, les systèmes automatisés utilisés pour harceler ou spammer, la manipulation artificielle des abonnements ou interactions et le contournement volontaire de mesures de modération.</>],
["10. Robots et automatisation",<>Les robots et automatisations ne sont pas interdits par principe.<br/><br/>Ils doivent toutefois respecter les règles de Kelo Social et ne pas être utilisés pour spammer, harceler, contourner les limites techniques, compromettre la sécurité ou manipuler artificiellement la plateforme.<br/><br/>Kelo Social peut limiter ou bloquer un système automatisé abusif.</>],
["11. Fraude et escroquerie",<>Les tentatives de fraude, phishing, escroquerie ou collecte trompeuse de données sont interdites.<br/><br/>Il est notamment interdit de se faire passer pour Kelo Social, Kelo ID, un administrateur, un certificateur ou un autre service afin d’obtenir des mots de passe, codes ou informations privées.</>],
["12. Données personnelles et vie privée",<>Les utilisateurs doivent respecter la vie privée des autres.<br/><br/>La publication non autorisée de données personnelles sensibles ou privées dans le but de nuire peut entraîner une intervention.<br/><br/>Les utilisateurs ne doivent jamais publier les mots de passe, codes de sécurité ou informations d’authentification d’une autre personne.</>],
["13. Propriété intellectuelle",<>Les utilisateurs doivent respecter les droits d’auteur, marques et autres droits de propriété intellectuelle.<br/><br/>Lorsqu’un contenu enfreint manifestement les droits d’un tiers, Kelo Social peut prendre les mesures appropriées après signalement ou constat.</>],
["14. Désinformation et informations trompeuses",<>Kelo Social ne souhaite pas devenir un arbitre général de toutes les opinions exprimées par ses utilisateurs.<br/><br/>Toutefois, certains contenus trompeurs peuvent faire l’objet d’une intervention lorsqu’ils sont associés à un risque sérieux, à une fraude, à une usurpation ou à une autre violation des règles.<br/><br/>Le contexte, l’intention et les risques liés au contenu peuvent être pris en compte.</>],
["15. Contenu sensible",<>Certains contenus pouvant être choquants sans être nécessairement interdits peuvent être étiquetés, masqués ou soumis à un avertissement.<br/><br/>Kelo Social peut notamment appliquer des mesures de visibilité aux contenus violents, graphiques, sexuellement explicites lorsqu’ils sont légalement autorisés ou sensibles pour certains utilisateurs.</>],
["16. Comptes certifiés",<>Un compte certifié ou un certificateur de confiance reste soumis aux mêmes règles de communauté que les autres utilisateurs.<br/><br/>Une certification n’accorde aucune immunité contre la modération.<br/><br/>Une violation grave ou répétée peut entraîner le retrait d’une certification en plus des autres mesures éventuelles.</>],
["17. Médias présents dans Journal",<>La présence d’un média dans <strong>Journal</strong> ne le dispense pas du respect des règles de Kelo Social.<br/><br/>Si un média enfreint gravement ou de manière répétée les règles applicables, Kelo Social peut notamment retirer certaines publications de ses interfaces lorsqu’il en a la possibilité, retirer le média de Journal ou appliquer les autres mesures prévues par la plateforme.</>],
["18. Signalement",<>Les utilisateurs peuvent signaler un contenu ou un compte à l’aide des outils disponibles sur Kelo Social.<br/><br/>Un signalement doit être effectué de bonne foi.<br/><br/>L’utilisation abusive et répétée des outils de signalement dans le but de harceler ou de faire supprimer injustement des contenus peut elle-même constituer un abus.</>],
["19. Examen des signalements",<>Kelo Social peut examiner notamment le contenu signalé, son contexte, l’historique pertinent du compte, la gravité de la violation, son caractère répété, les risques pour les utilisateurs et les obligations légales applicables.<br/><br/>Un signalement n’entraîne pas automatiquement une sanction.</>],
["20. Mesures de modération",<>Selon la nature d’une violation, Kelo Social peut notamment prendre les mesures suivantes : absence d’intervention ; avertissement ; ajout d’un avertissement de contenu ; limitation de visibilité ; retrait du contenu dans les services contrôlés par Kelo Social ; limitation de certaines fonctionnalités ; retrait d’une certification ; retrait de Journal ; suspension temporaire ; bannissement ou restriction durable dans les services contrôlés par Kelo Social.<br/><br/>La mesure choisie dépend notamment de la gravité et du contexte.</>],
["21. Fonctionnement décentralisé",<>Kelo Social utilise AT Protocol.<br/><br/>En conséquence, un contenu peut exister sur un PDS ou être indexé par d’autres services indépendants.<br/><br/>Une suppression ou un masquage effectué par Kelo Social ne signifie donc pas nécessairement que le contenu disparaîtra immédiatement de l’ensemble du réseau AT Protocol.<br/><br/>Kelo Social agit uniquement sur les services et composants qu’il contrôle effectivement.</>],
["22. Sanctions progressives",<>Lorsque cela est approprié, Kelo Social peut privilégier une approche progressive.<br/><br/>Une première violation mineure peut par exemple entraîner un avertissement, tandis que des violations répétées ou plus graves peuvent entraîner des restrictions plus importantes.<br/><br/>Certaines violations graves peuvent toutefois justifier une mesure immédiate sans avertissement préalable.</>],
["23. Contournement d’une sanction",<>La création ou l’utilisation d’un autre compte afin de contourner volontairement une restriction ou un bannissement peut entraîner des mesures supplémentaires.</>],
["24. Contestation d’une décision",<>Lorsqu’un mécanisme de contestation est disponible, l’utilisateur peut demander le réexamen d’une décision de modération.<br/><br/>La contestation doit idéalement expliquer pourquoi l’utilisateur estime que la décision doit être revue.<br/><br/>Kelo Social peut confirmer, modifier ou annuler la décision initiale après réexamen.</>],
["25. Signalements manifestement abusifs",<>Kelo Social peut prendre des mesures contre les personnes utilisant de manière répétée les mécanismes de signalement pour harceler un utilisateur, tenter de censurer artificiellement un adversaire ou multiplier volontairement de faux signalements.</>],
["26. Coopération avec les autorités",<>Kelo Social peut répondre aux demandes légalement valides des autorités compétentes lorsque la législation l’impose.<br/><br/>Kelo Social ne communique pas volontairement des données privées à un tiers en dehors d’un fondement juridique approprié.</>],
["27. Évolution des règles",<>Les présentes règles peuvent être modifiées afin de tenir compte de nouvelles fonctionnalités, de nouveaux risques, de changements techniques, de l’évolution de la législation ou de l’expérience acquise lors de la modération.<br/><br/>La date de dernière mise à jour est indiquée au début du document.</>],
["28. Contact",<><strong>Kelo Social</strong><br/><strong>M Maréchal</strong><br/><strong>Belgique — Province de Liège, Esneux</strong><br/><strong>E-mail :</strong> contact@kelosocial.eu</>],
] as const;

export default function CommunityRulesPage(){return <main className="min-h-screen bg-kelo-background px-4 py-10 text-kelo-text sm:px-6"><article className="mx-auto max-w-4xl rounded-3xl border border-kelo-border bg-white p-6 shadow-kelo sm:p-10"><Link href="/" className="text-sm font-bold text-kelo-primary hover:underline">← Retour à Kelo Social</Link><h1 className="mt-6 text-3xl font-black sm:text-4xl">Règles de la communauté et politique de modération — Kelo Social</h1><p className="mt-2 text-sm text-kelo-muted">Dernière mise à jour : Samedi 15 Août 2026</p><div className="mt-10 space-y-8 leading-7">{sections.map(([title,content])=><section key={title}><h2 className="text-xl font-extrabold">{title}</h2><div className="mt-3">{content}</div></section>)}</div></article></main>}
