import Link from "next/link";

export const metadata = { title: "Cookies et stockages locaux | Kelo Social" };

const sections = [
["1. Objet",<>La présente politique explique comment <strong>Kelo Social</strong> utilise les cookies, le stockage local du navigateur et les technologies similaires nécessaires au fonctionnement du service.<br/><br/>Kelo Social cherche à limiter l’utilisation de ces technologies à ce qui est nécessaire au fonctionnement, à la sécurité et aux préférences de l’utilisateur.</>],
["2. Qu’est-ce qu’un cookie ?",<>Un cookie est un petit fichier ou une information stockée par un navigateur ou un service web sur l’appareil de l’utilisateur.<br/><br/>Selon la technologie utilisée, ces informations peuvent servir notamment à maintenir une session, mémoriser une préférence ou assurer certaines fonctions techniques.</>],
["3. Stockage local du navigateur",<>Kelo Social peut utiliser le <strong>localStorage</strong>, le <strong>sessionStorage</strong> ou des technologies similaires du navigateur.<br/><br/>Ces mécanismes peuvent notamment être utilisés pour maintenir certaines informations de session, mémoriser des préférences d’affichage, conserver certains réglages de l’utilisateur, enregistrer localement des choix relatifs aux notifications et améliorer le fonctionnement de certaines fonctionnalités.<br/><br/>Ces informations sont stockées sur l’appareil de l’utilisateur jusqu’à leur suppression ou jusqu’à ce que Kelo Social les remplace ou les retire.</>],
["4. Cookies et technologies strictement nécessaires",<>Certaines technologies peuvent être nécessaires au fonctionnement de Kelo Social.<br/><br/>Elles peuvent notamment permettre la connexion au service, la sécurité des sessions, la prévention des abus, le fonctionnement de l’interface et le maintien de certaines préférences techniques.<br/><br/>Lorsque ces technologies sont strictement nécessaires au service demandé par l’utilisateur, leur utilisation peut ne pas nécessiter de consentement préalable dans les conditions prévues par la législation applicable.</>],
["5. Préférences utilisateur",<>Kelo Social peut enregistrer certaines préférences localement, par exemple le thème clair ou sombre, la langue de l’interface, les paramètres d’affichage, les réglages de notifications et les préférences liées aux fils et contenus affichés.<br/><br/>Ces données servent à éviter que l’utilisateur doive reconfigurer Kelo Social à chaque visite.</>],
["6. Authentification et AT Protocol",<>Certaines informations techniques peuvent être utilisées afin de maintenir ou restaurer une session liée à un compte <strong>AT Protocol</strong>.<br/><br/>Selon le fonctionnement du compte et du PDS utilisé, certaines informations techniques peuvent également être gérées par le fournisseur du PDS ou d’autres services de l’écosystème AT Protocol.<br/><br/>Ces services tiers peuvent appliquer leurs propres règles concernant les cookies ou stockages locaux.</>],
["7. Notifications",<>Lorsque l’utilisateur active les notifications système, le navigateur ou le système d’exploitation peut stocker certaines informations techniques nécessaires à leur fonctionnement.<br/><br/>Kelo Social peut également conserver localement les préférences de notification choisies par l’utilisateur.</>],
["8. Technologies de mesure ou statistiques",<>Kelo Social ne cherche pas à utiliser des cookies ou technologies similaires pour créer des profils publicitaires.<br/><br/>Si un outil de mesure d’audience ou d’analyse nécessitant le consentement de l’utilisateur devait être ajouté ultérieurement, Kelo Social mettrait à jour la présente politique et demanderait le consentement lorsque celui-ci est requis.</>],
["9. Publicité",<>Kelo Social n’utilise pas actuellement de cookies destinés à la publicité ciblée ou au suivi publicitaire des utilisateurs.<br/><br/>Kelo Social ne vend pas les données issues des cookies ou stockages locaux à des annonceurs.</>],
["10. Services tiers",<>Certains services utilisés avec Kelo Social peuvent déposer ou utiliser leurs propres technologies.<br/><br/>Cela peut notamment concerner certains PDS, des services AT Protocol et des fournisseurs techniques nécessaires au fonctionnement du site.<br/><br/>Lorsqu’une technologie est contrôlée directement par un service tiers, la politique de ce service peut également s’appliquer.</>],
["11. Gestion par le navigateur",<>L’utilisateur peut gérer ou supprimer les cookies et données locales depuis les paramètres de son navigateur.<br/><br/>La suppression de certaines données peut toutefois entraîner une déconnexion du compte, la perte de préférences, la désactivation de certaines fonctionnalités ou la nécessité de reconfigurer certains paramètres.</>],
["12. Consentement",<>Lorsque l’utilisation d’une technologie nécessite le consentement préalable de l’utilisateur, Kelo Social doit demander ce consentement avant son activation.<br/><br/>L’utilisateur doit pouvoir refuser ou retirer son consentement aussi facilement qu’il l’a donné, lorsque la législation applicable l’exige.</>],
["13. Durée de conservation",<>La durée de conservation dépend de la technologie et de sa finalité.<br/><br/>Certaines données peuvent être supprimées à la fermeture de la session ou du navigateur, tandis que d’autres peuvent rester stockées sur l’appareil afin de mémoriser les préférences de l’utilisateur.<br/><br/>Kelo Social cherche à ne pas conserver ces informations plus longtemps que nécessaire.</>],
["14. Sécurité",<>Kelo Social utilise ces technologies dans le but de permettre un fonctionnement stable et sécurisé du service.<br/><br/>Les informations stockées localement ne doivent pas être utilisées pour contourner les mesures de sécurité ou porter atteinte au compte d’un utilisateur.</>],
["15. Modifications",<>La présente politique peut être modifiée si Kelo Social ajoute de nouvelles fonctionnalités, si de nouveaux outils techniques sont intégrés, si les pratiques de stockage évoluent ou si la législation applicable change.<br/><br/>La date de dernière mise à jour est indiquée au début du document.</>],
["16. Contact",<><strong>Kelo Social</strong><br/><strong>M Maréchal</strong><br/><strong>Belgique — Province de Liège, Esneux</strong><br/><strong>E-mail :</strong> contact@kelosocial.eu</>],
] as const;

export default function CookiesPage(){return <main className="min-h-screen bg-kelo-background px-4 py-10 text-kelo-text sm:px-6"><article className="mx-auto max-w-4xl rounded-3xl border border-kelo-border bg-white p-6 shadow-kelo sm:p-10"><Link href="/" className="text-sm font-bold text-kelo-primary hover:underline">← Retour à Kelo Social</Link><h1 className="mt-6 text-3xl font-black sm:text-4xl">Politique relative aux cookies et stockages locaux — Kelo Social</h1><p className="mt-2 text-sm text-kelo-muted">Dernière mise à jour : Samedi 15 Août 2026</p><div className="mt-10 space-y-8 leading-7">{sections.map(([title,content])=><section key={title}><h2 className="text-xl font-extrabold">{title}</h2><div className="mt-3">{content}</div></section>)}</div></article></main>}
