"use client";

import { useMemo, useState } from "react";
import { LogOut } from "lucide-react";
import Sidebar from "@/components/layout/Sidebar";
import SettingsNav,{SettingsSection} from "@/components/settings/SettingsNav";
import AccountSection from "@/components/settings/AccountSection";
import IdentitySection from "@/components/settings/IdentitySection";
import DisplaySection from "@/components/settings/DisplaySection";
import ModerationSection from "@/components/settings/ModerationSection";
import PrivacySection from "@/components/settings/PrivacySection";
import NotificationFeedSection from "@/components/settings/NotificationFeedSection";
import LanguageContentSection from "@/components/settings/LanguageContentSection";
import MessagingSection from "@/components/settings/MessagingSection";
import LegalSection from "@/components/settings/LegalSection";
import { useRequireAuth } from "@/hooks/useRequireAuth";

const SECTION_TITLES:Record<SettingsSection,string>={account:"Compte et sécurité",identity:"Identité et domaine",moderation:"Modération",privacy:"Confidentialité",appearance:"Affichage",language:"Langues et centres d’intérêt",notifications:"Notifications et flux",messaging:"Messagerie",legal:"Informations juridiques"};
export default function SettingsPage(){const {checked,handle}=useRequireAuth();const [section,setSection]=useState<SettingsSection>("account");const sectionTitle=useMemo(()=>SECTION_TITLES[section],[section]);const handleLogout=()=>{localStorage.clear();window.location.href="/login"};if(!checked)return <div className="flex min-h-screen items-center justify-center bg-kelo-background font-sans text-kelo-muted">Vérification de votre session...</div>;
return <div className="flex min-h-screen w-full bg-kelo-background font-sans text-kelo-text"><Sidebar handle={handle} onLogout={handleLogout}/><main className="min-h-screen min-w-0 flex-1 bg-white pb-24 md:border-x md:border-kelo-border md:pb-0"><header className="sticky top-[calc(56px+env(safe-area-inset-top))] z-20 border-b border-kelo-border bg-white/95 px-4 py-3.5 backdrop-blur md:top-0 sm:px-5 md:py-4"><div className="mx-auto flex w-full max-w-6xl items-center justify-between gap-4"><div className="min-w-0"><h1 className="text-xl font-extrabold text-kelo-text">Paramètres</h1>{handle&&<p className="mt-0.5 truncate text-sm text-kelo-muted">@{handle}</p>}</div><button type="button" onClick={handleLogout} className="flex min-h-10 shrink-0 items-center gap-2 rounded-full border border-kelo-border px-3 text-sm font-bold text-kelo-muted transition hover:bg-red-50 hover:text-red-600 lg:hidden"><LogOut className="h-4 w-4"/><span className="hidden sm:inline">Déconnexion</span></button></div></header><div className="mx-auto grid w-full max-w-6xl lg:grid-cols-[300px_minmax(0,1fr)] xl:grid-cols-[320px_minmax(0,1fr)]"><aside className="border-b border-kelo-border lg:min-h-[calc(100vh-73px)] lg:border-b-0 lg:border-r"><SettingsNav active={section} onChange={setSection}/><div className="hidden border-t border-kelo-border p-3 lg:block"><button type="button" onClick={handleLogout} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold text-red-600 transition hover:bg-red-50"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-red-50"><LogOut className="h-[19px] w-[19px]"/></span>Se déconnecter</button></div></aside><section className="min-w-0 bg-white"><div className="border-b border-kelo-border px-4 py-3.5 sm:px-6 md:py-4"><h2 className="text-lg font-bold text-kelo-text">{sectionTitle}</h2></div><div className="settings-bluesky-section min-w-0">{section==="account"&&<AccountSection/>}{section==="identity"&&<IdentitySection/>}{section==="appearance"&&<DisplaySection/>}{section==="moderation"&&<ModerationSection/>}{section==="privacy"&&<PrivacySection/>}{section==="notifications"&&<NotificationFeedSection/>}{section==="language"&&<LanguageContentSection/>}{section==="messaging"&&<MessagingSection/>}{section==="legal"&&<LegalSection/>}</div></section></div></main></div>}
